# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondatetype',
            name='date_format',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='electiondatetype',
            name='time_format',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
