# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_fix_electiondatetype_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondate',
            name='kind',
            field=models.CharField(choices=[('DRD', 'Domestic Registration Deadline'), ('DBRD', 'Domestic Ballot Request Deadline'), ('DBED', 'Domestic Ballot Return Deadline'), ('ORD', 'Overseas Registration Deadline'), ('OBRD', 'Overseas Ballot Request Deadline'), ('OBED', 'Overseas Ballot Return Deadline'), ('MRD', 'Military Registration Deadline'), ('MBRD', 'Military Ballot Request Deadline'), ('MBED', 'Military Ballot Return Deadline'), ('EVF', 'Early Voting From'), ('EVT', 'Early Voting To'), ('AVF', 'In-Person Absentee Voting From'), ('AVT', 'In-Person Absentee Voting To')], default=('DRD', 'Domestic Registration Deadline'), max_length=4),
        ),
    ]
