# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models


def fix_election_dates(apps, schema):
    kinds = (
        ('DBSD', 'DBED'),
        ('OBSD', 'OBED'),
        ('MBSD', 'MBED'),
    )

    ElectionDate = apps.get_model('manager', 'ElectionDate')
    for (kind_old, kind_new) in kinds:
        ElectionDate.objects.filter(kind=kind_old).update(kind=kind_new)


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20160621_2106'),
    ]

    operations = [
        migrations.RunPython(fix_election_dates),
    ]
