# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_fix_election_dates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electiondate',
            unique_together=set([('election', 'kind', 'date_type')]),
        ),
    ]
