# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20160801_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader_name', models.CharField(blank=True, max_length=255)),
                ('uploader_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=64, null=True)),
                ('uploader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='manager.Election')),
                ('upload_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'election_result',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ElectionResultAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=1024, null=True)),
                ('file', models.FileField(upload_to=manager.models.upload_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manager.ElectionResult')),
            ],
            options={
                'db_table': 'election_result_attachment',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
