# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20170803_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='request_email_was_sent',
            field=models.IntegerField(default=0),
        ),
    ]
