# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20170828_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionresultdownloadhistory',
            old_name='download_at',
            new_name='downloaded_at',
        ),
        migrations.RenameField(
            model_name='electionresultdownloadhistory',
            old_name='download_by_user',
            new_name='downloaded_by_user',
        ),
    ]
