# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20170828_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
