# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20170831_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionresultattachment',
            name='notes',
        ),
    ]
