# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_remove_electionresultattachment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='use_default_elections_website',
            field=models.BooleanField(default=True),
        ),
    ]
