# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_election_use_user_email_as_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'State'), ('C', 'County'), ('CS', 'County Subdivision'), ('PL', 'Town/Place'), ('SE', 'School District Elementary'), ('SS', 'School District Secondary'), ('SU', 'School District Unified'), ('CD', 'Congressional District 114th')], db_index=True, default='U', max_length=2),
        ),
    ]
