# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20171128_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionTypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ['priority', 'name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'election_type_detail',
            },
        ),
        migrations.AddField(
            model_name='election',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_level',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_title',
            field=models.CharField(choices=[('EAR', 'Elections Administrator'), ('EOL', 'Election Official'), ('LEO', 'Local Election Official'), ('SOE', 'Supervisor of Elections'), ('VOR', 'Voter Registrar'), ('CMM', 'Commissioner'), ('CIK', 'Circuit Clerk'), ('CCK', 'City Clerk'), ('CTC', 'County Clerk'), ('DIC', 'District Clerk'), ('MUC', 'Municipal Clerk'), ('TCK', 'Town Clerk'), ('AVC', 'Absentee Voter Clerk'), ('ABC', 'Absentee Ballot Coordinator'), ('DCM', 'Democratic Commissioner'), ('RCM', 'Republican Commissioner'), ('VRR', 'Voter Registrar, Republican'), ('VRD', 'Voter Registrar, Democratic'), ('ACL', 'Assistant Clerk'), ('AEA', 'Assistant Elections Administrator'), ('ACI', 'Assistant Circuit Clerk'), ('ACC', 'Assistant County Clerk'), ('ADC', 'Assistant District Clerk'), ('AMC', 'Assistant Municipal Clerk'), ('ATC', 'Assistant Town Clerk'), ('DUC', 'Deputy Clerk'), ('DEC', 'Deputy Commissioner'), ('DDC', 'Deputy Democratic Commissioner'), ('DRC', 'Deputy Republican Commissioner'), ('DRR', 'Deputy Registrar'), ('OTH', 'Other')], default='EAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'State'), ('C', 'County'), ('PL', 'Town/Place')], db_index=True, default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='election',
            name='election_type_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.ElectionTypeDetail'),
        ),
    ]
