# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20180227_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(help_text='Enter name of election exactly how it appears on your sample ballot.', max_length=1024),
        ),
    ]
