# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20180307_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'election_administration_level',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AlterField(
            model_name='election',
            name='admin_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.AdministrationLevel'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'State'), ('C', 'County'), ('PL', 'Place'), ('DI', 'School District')], db_index=True, default='U', max_length=2),
        ),
    ]
