# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0002_auto_20171212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressofficer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_officers', to='eod.Address'),
        ),
        migrations.AlterField(
            model_name='addressofficer',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_addresses', to='eod.Officer'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='local_official',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='eod.LocalOfficial'),
        ),
    ]
