# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0003_auto_20171212_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
