# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0006_auto_20180111_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='main_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='main_fax_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='main_phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
