# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0007_auto_20180313_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localofficial',
            name='general_email',
        ),
        migrations.RemoveField(
            model_name='localofficial',
            name='website',
        ),
    ]
