# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0008_auto_20180313_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
