# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0009_auto_20180327_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='localofficial',
            name='geoid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
