# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0012_auto_20180424_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['order_number']},
        ),
    ]
