# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-25 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0013_auto_20180523_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='votingregion',
            options={'ordering': ['name']},
        ),
    ]
