# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-25 11:49
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0014_auto_20180525_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='localofficial',
            name='type',
            field=django_fsm.FSMField(choices=[('All', 'ALL'), ('Domestic', 'DOMESTIC'), ('UOCAVA', 'UOCAVA')], default='All', max_length=50),
        ),
    ]
