# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressionalDistrict114Th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('namelsad', models.TextField(blank=True, db_column='NAMELSAD', null=True)),
                ('cdsessn', models.IntegerField(blank=True, db_column='CDSESSN', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
            ],
            options={
                'db_table': 'congressional_district_114th',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyns', models.TextField(blank=True, db_column='COUNTYNS', null=True)),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('namelsad', models.TextField(blank=True, db_column='NAMELSAD', null=True)),
                ('classfp', models.TextField(blank=True, db_column='CLASSFP', null=True)),
                ('funcstat', models.TextField(blank=True, db_column='FUNCSTAT', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
                ('county_id', models.CharField(max_length=3, db_index=True, db_column='county_id')),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountySubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cousubns', models.TextField(blank=True, db_column='COUSUBNS', null=True)),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('namelsad', models.TextField(blank=True, db_column='NAMELSAD', null=True)),
                ('classfp', models.TextField(blank=True, db_column='CLASSFP', null=True)),
                ('funcstat', models.TextField(blank=True, db_column='FUNCSTAT', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
                ('county_id', models.CharField(max_length=3, db_index=True, db_column='county_id')),
            ],
            options={
                'db_table': 'county_subdivision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDistrictElementary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('lograde', models.TextField(blank=True, db_column='LOGRADE', null=True)),
                ('higrade', models.TextField(blank=True, db_column='HIGRADE', null=True)),
                ('sdtyp', models.TextField(blank=True, db_column='SDTYP', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
            ],
            options={
                'db_table': 'school_district_elementary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDistrictSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('lograde', models.TextField(blank=True, db_column='LOGRADE', null=True)),
                ('higrade', models.TextField(blank=True, db_column='HIGRADE', null=True)),
                ('sdtyp', models.TextField(blank=True, db_column='SDTYP', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
            ],
            options={
                'db_table': 'school_district_secondary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDistrictUnified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('lograde', models.TextField(blank=True, db_column='LOGRADE', null=True)),
                ('higrade', models.TextField(blank=True, db_column='HIGRADE', null=True)),
                ('sdtyp', models.TextField(blank=True, db_column='SDTYP', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
            ],
            options={
                'db_table': 'school_district_unified',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statens', models.TextField(blank=True, db_column='STATENS', null=True)),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('stusps', models.TextField(blank=True, db_column='STUSPS', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('aland', models.FloatField(blank=True, db_column='ALAND', null=True)),
                ('awater', models.FloatField(blank=True, db_column='AWATER', null=True)),
                ('intptlat', models.TextField(blank=True, db_column='INTPTLAT', null=True)),
                ('intptlon', models.TextField(blank=True, db_column='INTPTLON', null=True)),
                ('state_id', models.CharField(max_length=2, db_index=True, db_column='state_id')),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
