# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electiongis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congressionaldistrict114th',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countysubdivision',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schooldistrictelementary',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schooldistrictsecondary',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schooldistrictunified',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
    ]
