# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electiongis', '0002_auto_20160621_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.TextField(blank=True, db_column='GEOID', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('fips', models.TextField(blank=True, db_column='FIPS', null=True)),
                ('state_id', models.CharField(db_column='state_id', db_index=True, max_length=2)),
                ('county_id', models.CharField(db_column='county_id', db_index=True, max_length=3)),
                ('place_id', models.CharField(db_column='place_id', db_index=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
