
LOCATION_TYPE_UNKNOWN                       = "U"
LOCATION_TYPE_STATE                         = "S"
LOCATION_TYPE_COUNTY                        = "C"
LOCATION_TYPE_COUNTY_SUBDIVISION            = "CS"
LOCATION_TYPE_PLACE                         = "PL"
LOCATION_TYPE_DISTRICT                      = "DI"
LOCATION_TYPE_SCHOOL_DISTRICT_ELEMENTARY    = "SE"
LOCATION_TYPE_SCHOOL_DISTRICT_SECONDARY     = "SS"
LOCATION_TYPE_SCHOOL_DISTRICT_UNIFIED       = "SU"
LOCATION_TYPE_CONGRESSIONAL_DISTRICT_114TH  = "CD"

LOCATION_TYPE_PREFIXES = (LOCATION_TYPE_STATE, LOCATION_TYPE_COUNTY, LOCATION_TYPE_COUNTY_SUBDIVISION, LOCATION_TYPE_PLACE, LOCATION_TYPE_SCHOOL_DISTRICT_ELEMENTARY, LOCATION_TYPE_SCHOOL_DISTRICT_SECONDARY, LOCATION_TYPE_SCHOOL_DISTRICT_ELEMENTARY, LOCATION_TYPE_SCHOOL_DISTRICT_UNIFIED, LOCATION_TYPE_CONGRESSIONAL_DISTRICT_114TH)

LOCATION_TYPE = (
    (LOCATION_TYPE_UNKNOWN, 'Unknown'),
    (LOCATION_TYPE_STATE, 'State'),
    (LOCATION_TYPE_COUNTY, 'County'),
    # (LOCATION_TYPE_COUNTY_SUBDIVISION, 'County Subdivision'),
    (LOCATION_TYPE_PLACE, 'Place'),
    (LOCATION_TYPE_DISTRICT, 'School District'),
    # (LOCATION_TYPE_SCHOOL_DISTRICT_ELEMENTARY, 'School District Elementary'),
    # (LOCATION_TYPE_SCHOOL_DISTRICT_SECONDARY, 'School District Secondary'),
    # (LOCATION_TYPE_SCHOOL_DISTRICT_UNIFIED, 'School District Unified'),
    # (LOCATION_TYPE_CONGRESSIONAL_DISTRICT_114TH, 'Congressional District 114th'),
)

LOCATION_TYPE_API = dict(zip(
    LOCATION_TYPE_PREFIXES,
    ('state', 'county', 'county_subdivision', 'place', 'school_district_elementary', 'school_district_secondary', 'school_district_unified', 'congressional_district_114th',)
))
