export enum CallStatus {
	SET_SHOW_CALLING_BOX = 'SET_SHOW_CALLING_BOX',
	SET_TITLE = 'SET_TITLE',
	SET_STATUS = 'SET_STATUS',
	SET_IS_INBOUND = 'SET_IS_INBOUND',
	SET_RECORDING = 'SET_RECORDING',
	SET_ON_HOLD = 'SET_ON_HOLD',
	SET_MUTED = 'SET_MUTED',
	SET_KEYPAD = 'SET_KEYPAD',
	SET_SHOW_RECONNECT_CALL_TO_CELL_MODAL = 'SET_SHOW_RECONNECT_CALL_TO_CELL_MODAL',
}
