export enum EDialStatus {
	NOT_READY = 'S_DIAL_NOT_READY',
	SET_TOKEN = 'S_SET_TOKEN',
	NEED_EVENT_HANDLER = 'S_NEED_EVENT_HANDLER',
	READY = 'S_DIAL_READY',
	INBOUND_RING = 'S_DIAL_INBOUND_RING',
	INBOUND_IN_CALL = 'S_DIAL_INBOUND_IN_CALL',
	INBOUND_END_CALL = 'S_DIAL_INBOUND_END_CALL',
	OUTBOUND_RING = 'S_DIAL_OUTBOUND_RING',
	OUTBOUND_RINGING = 'S_DIAL_OUTBOUND_RINING_CALL',
	OUTBOUND_IN_CALL = 'S_DIAL_OUTBOUND_IN_CALL',
	OUTBOUND_END_CALL = 'S_DIAL_OUTBOUND_END_CALL',
}
